version: '3'
services:
  master:
    build: ./server
    container_name: master
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLASK_ENV: development
    tty: true
