version: '3'
services:
  fed-srv:
    build: .
    container_name: fed-srv
    ports:
      - "5001:5001"
    volumes:
      - .:/mnt/app
    environment:
      FLASK_ENV: development
    tty: true
  